### ISSUE TITLE
APNGImageView is not recognized by Xcode 7 in storyboard

### ISSUE THREAD

**Issue by yurijmi** [onevcat/APNGKit#4]
Autocomplete does not work and Xcode doesn't allow me to use it at all because of that.

![2015-10-21 11 26 18](https://cloud.githubusercontent.com/assets/785492/10631431/b020c22c-77e6-11e5-92b1-eefe09d4227f.png)

Although I can use APNGKit's functions in code.

Am I doing something wrong? Or is there a bug in your code?

**Comment by onevcat** [comment]
I guess it is an Xcode bug instead of APNGKit.

Did you try type `APNGImageView` as the Class and `APNGKit` as the Module directly? It should work if you setup the framework correctly.

**Comment by yurijmi** [comment]
Same with module. Autocomplete doesn't work and Xcode doesn't accept APNGKit directly.
I believe I set up everything correctly. Like I said earlier, everything works from code.

**Comment by onevcat** [comment]
What do you mean by "Xcode doesn't accept APNGKit directly"? Do you get a compile error when using "APNGImageView" and "APNGKit"?

I just had a try on using it from IB. Sure, the auto completion does not work for me, but I could get things work correctly by just setting them to "APNGImageView" and "APNGKit", then doing regular Ctrl+Drag IBOutlet things and setup the apng images without issue.

**Comment by yurijmi** [comment]
By directly I mean typing everything without autocomplete. Xcode clears the field after I go out of it.

**Comment by onevcat** [comment]
:[

Xcode, good job!

May I know how did you integrate APNGKit into your project? By Carthage or CocoaPods? I tried Carthage just now and it seems OK.

**Comment by yurijmi** [comment]
CocoaPods

**Comment by onevcat** [comment]
Cool. I can reproduce it in CocoaPods. Let me see what I can do...

**Comment by onevcat** [comment]
Oh, I know.

Instead of using an image view, you need a `UIView` for it. Since `APNGImageView` is NOT a subclass of `UIImageView`.

**Comment by yurijmi** [comment]
What's a I thought. I'll try it now.

**Comment by yurijmi** [comment]
Yeah, it works for View. Thanks for your support!
But why not UIImageView for parent? Is it not working for APNG?
AnimatedGIFImageSerialization and FLAnimatedImage is based of a UIImageView and working without problems.

**Comment by onevcat** [comment]
It might be better to be a subclass of `UIImageView`. I will reconsider it and give it a fix if necessary. Thank you.

**Comment by yurijmi** [comment]
What do you think? Maybe just extend UIImageView and UIImage like AnimatedGIFImageSerialization did?
Or is it a bad thing to do?

**Comment by onevcat** [comment]
The initializer of Swift would be a pain, if we want to keep the same signage for APNGImageView as the regular image view. Since APNGKit is written in Swift, its type is not as flexible as which in Objective-C. 
Anyway, I think there would be a solution for it (the worst is some API adjustment).

I will have a look at it later.

**Comment by yurijmi** [comment]
Thanks a ton! Man, you rock!

**Comment by onevcat** [comment]
@yurijmi Just had a try on changing to image view, and I found it might break quite a lot of current APIs if I do so. In short word, I decide to keep it a subclass of `UIView` now.

I recalled why it is a `UIView` as well. At the very beginning, `APNGImageView` was designed to use the same APIs as regular `UIImageView` for connivence. This made it not quite suitable to be a subclass of `UIImageView`. There are already some animating-related APIs for playing a sequence of images in `UIImageView`. If we override these methods to keep usage the same, it will be quite confusing how exactly the class should work. However, if we do not do so but use a new set of APIs, it is another level of compatibility for users. At last, I decided to "reimplement" the main behavior of the animated image view and it turned out to be the `APNGImageView` now.

I guess I should add some explanation in README to clarify it later.
