### ISSUE TITLE
returns image is nil

### ISSUE THREAD

**Issue by YKV** [onevcat/APNGKit#54]
I have an apng image that has 200 frames and extension of pang image is .png
Whenever I do:

apngView = APNGImageView(image: image)

image is nil even though the image exists in assets

I am using Xcode9

**Comment by onevcat** [comment]
Please check this: https://github.com/onevcat/APNGKit#png-compression

**Comment by fumiyasac** [comment]
I cause the same issue, too.
In XCode9, I can't find COMPRESS_PNG_FILES setting.
So, I don't know how to solve this.

**Comment by onevcat** [comment]
@fumiyasac You should not use it in an image asset set. Please add your APNG files to your project directly. In fact, I suggest to use another extension like "apng" instead of disabling PNG compression since you might still want it for other png images.

Maybe this post would be a help: https://stackoverflow.com/questions/33082838/compress-png-files-missing-from-build-settings
